version: "3"

services:

  visualizer:
    image: manomarks/visualizer:latest
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOST=localhost
    networks:
      - events-network
    deploy:
      placement:
        constraints: [node.role == manager]

  zk:
    image: vitalcode/events-zookeeper
    ports:
      - 2181:2181
    networks:
      - events-network
    deploy:
      placement:
        constraints: [node.role == manager]

  kafka:
    image: vitalcode/events-kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zk:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://$${HOSTNAME}:9092
      - KAFKA_DELETE_TOPIC_ENABLE=true
    ports:
      - 9092:9092
    networks:
      - events-network
    deploy:
      mode: global

networks:
  events-network:
