version: "3"

services:

  visualizer:
    image: manomarks/visualizer:latest
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOST=localhost
    networks:
      - events-network
    deploy:
      placement:
        constraints: [node.role == manager]

  logspout:
    depends_on:
      - kafka
    image: vitalcode/events-logspout-logstash
    ports:
      - 8000:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - events-network
    command: syslog://logstash:5000
    deploy:
      placement:
        constraints: [node.role == worker]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - events-network
    environment:
      - cluster.name=elastic-log
      - http.cors.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    deploy:
      placement:
        constraints: [node.role == worker]

  logstash:
    depends_on:
      - logspout
      - elasticsearch
    image: vitalcode/events-logstash
    environment:
      LOGSPOUT: ignore
    networks:
      - events-network
    deploy:
      placement:
        constraints: [node.role == manager]

  kibana:
    depends_on:
      - logspout
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:5.3.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - events-network
    deploy:
      placement:
        constraints: [node.role == manager]

  zk:
    image: vitalcode/events-zookeeper
    ports:
      - 2181:2181
    networks:
      - events-network
    deploy:
      placement:
        constraints: [node.role == manager]

  kafka:
    depends_on:
      - zk
    image: vitalcode/events-kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zk:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://$${HOSTNAME}:9092
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - "KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=$$(dig +short myip.opendns.com @resolver1.opendns.com) -Dcom.sun.management.jmxremote.rmi.port=1099 "
      - JMX_PORT=1099
    ports:
      - 9092:9092
      - 1099:1099
    networks:
      - events-network
    deploy:
      placement:
        constraints: [node.role == worker]

networks:
  events-network:

