version: "3"

services:

  elasticsearch:
    image: ypereirareis/elasticsearch-head:1.7.5
    command:
      - -Des.http.cors.enabled=true
      - -Des.cluster.name=robotic
      - -Des.index.number_of_shards=5
      - -Des.index.number_of_replicas=0
      - -Des.discovery.zen.ping.unicast.hosts=elasticsearch
      - -Des.node.master=true
      - -Des.node.data=true
      - -Des.iscovery.zen.minimum_master_nodes=1
      - -Des.discovery.zen.ping.multicast.enabled=false
      - -Des.network.publish_host=elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elasticsearch-net
    deploy:
      placement:
        constraints: [node.role == manager]

  elasticsearch-data:
    image: ypereirareis/elasticsearch-head:1.7.5
    command:
      - -Des.http.cors.enabled=true
      - -Des.cluster.name=robotic
      - -Des.index.number_of_shards=5
      - -Des.index.number_of_replicas=0
      - -Des.discovery.zen.ping.unicast.hosts=elasticsearch
      - -Des.node.master=false
      - -Des.node.data=true
      - -Des.iscovery.zen.minimum_master_nodes=1
      - -Des.discovery.zen.ping.multicast.enabled=false
      - -Des.network.publish_host=$${HOSTNAME}
    networks:
      - elasticsearch-net
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]

  postgres:
    image: vitalcode/events-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    networks:
      - elasticsearch-net
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=development
      - POSTGRES_USER=user
      - POSTGRES_DB=events
      - EVENTS_APP_USER=${EVENTS_APP_USER}
      - EVENTS_APP_PASSWORD=${EVENTS_APP_PASSWORD}
    deploy:
      labels:
        [uk.vitalcode.events.role=database]
      placement:
        constraints: [node.role == manager]

  events-api:
    image: vitalcode/events-api
    environment:
      - PSQL_URL=jdbc:postgresql://postgres/events
      - PSQL_USER=user
      - PSQL_PASSWORD=development
      - ES_URL=elasticsearch://elasticsearch:9300
      - ES_INDEX=lisenok
      - ES_TYPE=events
      - ES_CLUSTER=robotic
    depends_on:
      - elasticsearch
      - postgres
    ports:
      - 8083:8083
    networks:
      - elasticsearch-net
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]

  graphiql:
    image: vitalcode/auth-graphiql
    ports:
      - 3000:3000
    depends_on:
      - events-api
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]

networks:
  elasticsearch-net:

volumes:
  postgres-data:

#  proxy:
#    image: vitalcode/events-proxy
#    #restart: always
#    ports:
#      - "8080:8080"
#    links:
#      - events-api
#    labels:
#      uk.vitalcode.events.role: "proxy"
#    networks:
#      - events-network
#    deploy:
#      placement:
#        constraints: [node.role == manager]


