version: "3"

services:

  elasticsearch-master:
    image: ypereirareis/elasticsearch-head:1.7.5
    command:
      - -Des.http.cors.enabled=true
      - -Des.cluster.name=lisenok
      - -Des.index.number_of_shards=5
      - -Des.index.number_of_replicas=0
      - -Des.discovery.zen.ping.unicast.hosts=elasticsearch-master
      - -Des.node.master=true
      - -Des.node.data=true
      - -Des.iscovery.zen.minimum_master_nodes=1
      - -Des.discovery.zen.ping.multicast.enabled=false
      - -Des.network.publish_host=elasticsearch-master
    ports:
      - 9200:9200
    networks:
      - elasticsearch-net
    deploy:
      placement:
        constraints: [node.role == manager]

  elasticsearch-data:
    image: ypereirareis/elasticsearch-head:1.7.5
    command:
      - -Des.http.cors.enabled=true
      - -Des.cluster.name=lisenok
      - -Des.index.number_of_shards=
      - -Des.index.number_of_replicas=0
      - -Des.discovery.zen.ping.unicast.hosts=elasticsearch-master
      - -Des.node.master=false
      - -Des.node.data=true
      - -Des.iscovery.zen.minimum_master_nodes=1
      - -Des.discovery.zen.ping.multicast.enabled=false
      - -Des.network.publish_host=$${HOSTNAME}
    networks:
      - elasticsearch-net
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]

  postgres:
    image: postgres:9.6.1
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    networks:
      - events-network
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=development
      - POSTGRES_USER=user
      - POSTGRES_DB=events
    deploy:
      labels:
        [uk.vitalcode.events.role=database]
      placement:
        constraints: [node.role == manager]

  events-api:
    image: vitalcode/events-api
    environment:
        - PSQL_URL=jdbc:postgresql://postgres:5432/events
        - PSQL_USER=user
        - PSQL_PASSWORD=development
        - ES_URL=elasticsearch://elasticsearch-master:9300
        - ES_INDEX=lisenok
        - ES_TYPE=events
        - ES_CLUSTER=robotic
    depends_on:
      - elasticsearch-master
      - postgres
    ports:
      - 8083:8083
    networks:
      - elasticsearch-net
      - events-network
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]

  graphiql:
    image: vitalcode/auth-graphiql
    ports:
      - 3000:3000
    depends_on:
      - events-api
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]

networks:
  elasticsearch-net:
  events-network:

volumes:
  postgres-data:

#  proxy:
#    image: vitalcode/events-proxy
#    #restart: always
#    ports:
#      - "8080:8080"
#    links:
#      - events-api
#    labels:
#      uk.vitalcode.events.role: "proxy"
#    networks:
#      - events-network
#    deploy:
#      placement:
#        constraints: [node.role == manager]


